language: java
jdk:
  - oraclejdk8
before_install:
  - git clone git@github.com:belakede/thesis-core.git /tmp/thesis-core
  - mvn install -Dmaven.test.skip=true -f /tmp/thesis-core/pom.xml
  - git clone git@github.com:belakede/thesis-channel.git /tmp/thesis-channel
  - mvn install -Dmaven.test.skip=true -f /tmp/thesis-channel/pom.xml
after_script:
  - rm -rf /tmp/thesis-core
  - rm -rf /tmp/thesis-channel